# Generated by Django 2.0 on 2017-12-21 08:18

from django.db import migrations, models
import django.db.models.deletion
import docs.models
import markdownx.models
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'doc',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PageContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('basedoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='docs.BaseDoc')),
            ],
            options={
                'abstract': False,
            },
            bases=('docs.basedoc',),
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('basedoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='docs.BaseDoc')),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'abstract': False,
            },
            bases=('docs.basedoc',),
        ),
        migrations.AddField(
            model_name='pagecontentitem',
            name='doc',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='docs.BaseDoc'),
        ),
        migrations.AddField(
            model_name='basedoc',
            name='content_type',
            field=models.ForeignKey(on_delete=models.SET(docs.models.base.get_default_form_content_type), related_name='docs', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='pagecontentitem',
            name='snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.Snippet'),
        ),
    ]
