# Generated by Django 2.0 on 2017-12-21 13:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedoc',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags', blank=True),
        ),
    ]
