# Generated by Django 2.0 on 2017-12-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_basedoc_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedoc',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
