# Generated by Django 2.0 on 2017-12-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_basedoc_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='linked_pages',
            field=models.ManyToManyField(blank=True, related_name='_page_linked_pages_+', to='docs.Page'),
        ),
    ]
