# Generated by Django 4.2.5 on 2023-09-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docs", "0006_basedoc_users_editable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="linked_pages",
            field=models.ManyToManyField(blank=True, to="docs.page"),
        ),
    ]
